sudo: false
language: c

env:
  global:
    - RACKET_DIR=~/racket
    - PATH=./racket/bin:$PATH 
  matrix:
    - RACKET_VERSION=HEAD
before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"
before_install:
  - git clone --depth=1 https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
script:
 - make cs RACKET="${RACKET_DIR}/bin/racket" CPUS="2" PKGS="racket-test-core compiler-lib" -j 2
 - ./racket/bin/raco test -l tests/racket/test
 - ./racket/bin/racocs test -l tests/racket/test
 - racocs test -l tests/racket/test
notifications:
  slack:
    secure: A19kphrabQHO8TU6qZcBaLQxdSNpm1ypEtbQsh8Ucg6HYPP7y1q7O7JZEndoMRHE9CNKZ9oXQzqR8H1IFVTlnjFFIJfkZzZ1YSNk4abSomhpWCq9daKMfwlcuTtY6PeI1nDVpka4/hiJGn9qzmaKYXle9Sl4CX2VEYp8o8PgMEs=
    rooms:
      secure: FsKzp4ItmOqd/YxqgsElgfjGW2/TU03p2p3ss+PQl/pKDQNnR/2b4pWCQ7GuqYibkmtiH1jYwrnuaLN4Cc+JyN7Z+zUtO4VSORsh3zt/gTsfgphMpCP6cB4sTqUh6AWsZOgzikj+fh7ORHEXVswQwlRHErTgZVEdEkWHBh4UWzc=
