name: Snapshot Generation

on:
  push:
    branches:
      - master

jobs:
  create-installer:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: Bogdanp/setup-racket@v0.8
      with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: 'current'
          

    - name: Building
      env:
        DISTRO_BUILD_SITE_DEST: "${{ runner.temp }}/site-dest/"
      run: |
        export cpus=$(grep -c ^processor /proc/cpuinfo)
        make snapshot-site PLAIN_RACKET=/usr/bin/racket CONFIG=".github/workflows/site-small.rkt" -j $((cpus+1))

    # - name: S3 Sync
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWSAccessKeyID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSecretKey }}
    #   run: |
    #     ls -l ${{ runner.temp }}/site-dest/ci-snapshots/
    #     raco s3-sync --acl public-read --web --redirect-links ${{ runner.temp }}/site-dest/ci-snapshots/ s3://snapshot.racket-lang.org/ci-snapshots/
